# Generated by Django 5.1.4 on 2025-02-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobidder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='domain',
            field=models.OneToOneField(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bet', serialize=False, to='autobidder_app.domain'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='max_bet',
            field=models.IntegerField(),
        ),
    ]
